### ISSUE TITLE
Support for digit-only OCR

### ISSUE THREAD

**Issue by torre76** [jflesch/pyocr#17]
Hello,

I am using your library in conjunction with Tesseract to recognize digit-only images.
On the first try, Tesseract had some issues with some digit like "0" taken as "D" and so on until I notice there is a parameter for Tesseract to instruct it that the image contains only digit.
Doing so the recognition is perfect (99%).

To activate this feature (that is, adding *digits* to the Tessetact command line), I subclassed the Text Builder this way:

```python

class DigitBuilder(TextBuilder):
            """
                Specialization for Tesseract to use Digit Only recognition
            """

            def __init__(self, tesseract_layout=3):
                self.tesseract_configs = ["-psm", str(tesseract_layout), "digits"]
```

I would like to write a pull request on it, but I do not know how you manage the builders and if *Cuneiform* has a similar feature.

If you provide me some hints I will surely help this useful project.
Regards

**Comment by jflesch** [comment]
f36f2492
