### ISSUE TITLE
Unnecessary file IO

### ISSUE THREAD

**Issue by ventsyv** [jflesch/pyocr#19]
The way the image_to_string functions are currently implemented, the output of the engine is written to file, which is then read in and returned to the user.
Both Cuneiform and Tesseract now support sending the output to stdout thus eliminating the need for the 2 extra file IO operations.
I'll attempt implementing this - hopefully it will result in speeding things up a bit.

**Comment by jflesch** [comment]
#30 should fix this issue as well (for Tesseract)

**Comment by jflesch** [comment]
#30 has been implemented. It fixes this issue.
