### ISSUE TITLE
Direct file input

### ISSUE THREAD

**Issue by ventsyv** [jflesch/pyocr#22]
Both tesseract and cuneiform allow the user to pass in a file name as input. I would like to add a function that will take a file name directly and pass it to the OCR engine, rather than having to create a temporary input file. Since I was not able to replace the file IO with memory pipe for tesseract, having a function like that will speed things up since it will eliminate the unnecessary file IO.

**Comment by jflesch** [comment]
Actually, #30 should fix this problem as well.

**Comment by ventsyv** [comment]
Yes it will. I was thinking about implementing it, but did not have the time. Let me check how much of it I've implemented and I'll either merge it or close the issue. I might have some time this weekend to take on #30.

**Comment by jflesch** [comment]
#30 has been implemented. If there is still a problem for you (Cuneiform ?), please add a comment here and I will reopen this ticket.
