### ISSUE TITLE
Inconsistent spelling of Pyocr/PyOCR

### ISSUE THREAD

**Issue by plietar** [jflesch/pyocr#24]
Hi Jerome,
What is the exact spelling of the project ? The README uses PyOCR in the title but Pyocr in the description.
This may sound like nitpicking but debian requires me to specify the case-sensitive name of the project.

Would you mind changing all occurrences to one of the spellings ?

Thanks !

**Comment by jflesch** [comment]
That's actually a question I've been asking myself for a long time .... :-)
Which one do you prefer ?

**Comment by plietar** [comment]
Personally, I'd go for PyOCR, but either would do.

**Comment by jflesch** [comment]
As you said either would. So let's go for PyOCR. :-)

**Comment by jflesch** [comment]
Done: a8c288ffd8d2be38d33cee3c4508265a2f294966
