### ISSUE TITLE
Tesseract test fails on test_orientation_90, KeyError "Uknown Extension"

### ISSUE THREAD

**Issue by jalavosus** [jflesch/pyocr#29]
Error output:
    Tesseract:
    ........................E
    ======================================================================
    ERROR: test_orientation_90 (tests.tests_tesseract.TestOrientation)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/james/pyocr/tests/tests_tesseract.py", line 352, in test_orientation_90
        result = tesseract.detect_orientation(img, lang='eng')
      File "src/pyocr/tesseract.py", line 159, in detect_orientation
        image.save(proc.stdin, format=image.format)
      File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1453, in save
        raise KeyError(ext) # unknown extension
    KeyError: ''

I'm using the <code>python-imaging</code> library from Ubuntu's repositories. This is the only test that fails. Please advise on how to fix.

**Comment by jflesch** [comment]
Hm, weird. It looks like your python-imaging lacks PNG support.

**Comment by jflesch** [comment]
in src/pyocr/tesseract.py, you can try replacing
```
    image.save(proc.stdin, format='png')
```

by something like

```
    image.save(proc.stdin, format='bmp')
```

**Comment by jalavosus** [comment]
This is interesting; my version of Image does support PNG -- it actually has more trouble with JPG's than it does PNG's. 

Nothing's broken besides the last test, so I won't worry about it. Closing the issue.
