### ISSUE TITLE
Tesseract __init__.py not working. 

### ISSUE THREAD

**Issue by soumik862003** [jflesch/pyocr#46]
>>> import tesseract
  File "C:\Users\<USER NAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\tesseract\__init__.py", line 34
    print 'Creating user config file: {}'.format(_config_file_usr)
                                                     ^
SyntaxError: invalid syntax
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

there at the line 34 it shows like this:

![image](https://cloud.githubusercontent.com/assets/23091424/19754668/29207dc8-9c2d-11e6-837b-b5275c1600db.png)

**Comment by jflesch** [comment]
There is no file ```tesseract_init_.py``` and no message "Creating user config file:{}" in PyOCR. I think you reported this to the wrong developer / library.

**Comment by jflesch** [comment]
Btw, for PyOCR, the basic import is [```import pyocr```](https://github.com/jflesch/pyocr) and not ```import tesseract```.

**Comment by jflesch** [comment]
I believe you have been trying to use this package : https://pypi.python.org/pypi/tesseract/0.1.3
It has nothing to do with OCR or Google's Tesseract.

If you actually want to work with OCR, I suggest you uninstall 'tesseract' first (```sudo pip uninstall tesseract``` / ```sudo pip3 uninstall tesseract```) and install and use [PyOCR](https://github.com/jflesch/pyocr#installation) for instance.
