### ISSUE TITLE
ImportError: No module named builders

### ISSUE THREAD

**Issue by kumarivin** [jflesch/pyocr#53]
I am getting the below error while executing a script mentioned in initialization section of the readme file

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyocr/__init__.py", line 1, in <module>
    from .pyocr import *
  File "/usr/local/lib/python2.7/dist-packages/pyocr/pyocr.py", line 50, in <module>
    from . import tesseract
  File "/usr/local/lib/python2.7/dist-packages/pyocr/tesseract.py", line 28, in <module>
    from pyocr.builders import DigitBuilder  # backward compatibility

**Comment by jflesch** [comment]
Hello,

I think you truncated the error message. It should have been one line below.

**Comment by jflesch** [comment]
Nevermind, I can reproduce it. A contrib broke python 2.7 support.

**Comment by jflesch** [comment]
def5c07eb08c1f8964e548fe2c17b8f5c2cfd3f0
I'll release Pyocr 0.4.4 asap to fix this issue.
Sorry for the mess

**Comment by jflesch** [comment]
0.4.4 released on Pypi (--> ```pip install -U pyocr```)

**Comment by kumarivin** [comment]
@jflesch  sorry for the late response and thanks a ton !!
