### ISSUE TITLE
Langs: can more languages be supported? 

### ISSUE THREAD

**Issue by fangfangbest** [jflesch/pyocr#56]
i have got equ, eng and osd in the language list and if it is possible to support other languages like Chinese

**Comment by jflesch** [comment]
The list of languages available depends on what's installed on your system.

For example, on Ubuntu/Debian/etc, if you use Tesseract, you can install the Chinese data files with the following command:
```sudo apt install tesseract-ocr-chi-sim tesseract-ocr-chi-tra```
(chi-sim = simplified Chinese ; chi-tra = traditional Chinese).

For a complete list of supported languages:
```apt search tesseract-ocr-``` / [Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-304)
