### ISSUE TITLE
Add support for Scribo

### ISSUE THREAD

**Issue by jflesch** [jflesch/pyocr#6]
Suggested on [Linuxfr.org](http://linuxfr.org/users/jflesch/journaux/paperwork-besoin-de-testeurs#comment-1449338) :
http://www.lrde.epita.fr/cgi-bin/twiki/view/Olena/Modules#SCRIBO

**Comment by jflesch** [comment]
Looks dead : http://www.scribo.ws/

**Comment by amitdo** [comment]
https://github.com/glazzara/olena

**Comment by jflesch** [comment]
@amitdo no new commit for about 4 years :/
